[package]
name = "word-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docx-rs = "0.4.6"
docx = "1.1.2"
eframe = "0.21.3"
rfd = "0.11.2"
tracing-subscriber = "0.3"
